#!/usr/bin/env bash
# =============================================================================
# Symphony After-Run Hook
# 在 Agent 完成任务后自动执行：
#   1. git commit & push 分支到 GitHub
#   2. 创建 GitHub Pull Request
#   3. 更新 Linear Issue 状态为 "In Review"
# =============================================================================

set -euo pipefail

# -----------------------------------------------------------------------------
# 加载环境变量（从项目根目录的 .env）
# -----------------------------------------------------------------------------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
ENV_FILE="$PROJECT_ROOT/.env"

if [ -f "$ENV_FILE" ]; then
  # 只导出非注释、非空行
  set -o allexport
  # shellcheck disable=SC1090
  source <(grep -E '^[A-Za-z_][A-Za-z0-9_]*=' "$ENV_FILE")
  set +o allexport
fi

# -----------------------------------------------------------------------------
# 从工作区路径推断 Issue Identifier（例如 INT-10）
# 当前工作目录就是 workspace 目录（orchestrator 以 cwd=workspacePath 运行 hook）
# -----------------------------------------------------------------------------
WORKSPACE_PATH="$(pwd)"
ISSUE_IDENTIFIER="$(basename "$WORKSPACE_PATH")"

echo "[after-run] Workspace: $WORKSPACE_PATH"
echo "[after-run] Issue: $ISSUE_IDENTIFIER"

# -----------------------------------------------------------------------------
# 必要变量校验
# -----------------------------------------------------------------------------
GITHUB_TOKEN="${GITHUB_TOKEN:-}"
GITHUB_OWNER="${SYMPHONY_GITHUB_OWNER:-${GITHUB_OWNER:-}}"
GITHUB_REPO="${SYMPHONY_GITHUB_REPO:-${GITHUB_REPO:-}}"
GITHUB_DEFAULT_BRANCH="${GITHUB_DEFAULT_BRANCH:-main}"
LINEAR_API_KEY="${SYMPHONY_TRACKER_API_KEY:-}"
LINEAR_IN_REVIEW_STATE_ID="2d55ad60-e9a3-4490-a78d-d8ddd0f5e45a"

if [ -z "$GITHUB_TOKEN" ] || [ -z "$GITHUB_OWNER" ] || [ -z "$GITHUB_REPO" ]; then
  echo "[after-run] WARNING: GitHub config missing (GITHUB_TOKEN/GITHUB_OWNER/GITHUB_REPO), skipping PR creation."
  exit 0
fi

# -----------------------------------------------------------------------------
# Step 1: Git commit & push
# -----------------------------------------------------------------------------
echo "[after-run] Staging and committing changes..."

# 检查是否有改动
if git diff --quiet && git diff --staged --quiet && [ -z "$(git ls-files --others --exclude-standard)" ]; then
  echo "[after-run] No changes to commit, skipping."
else
  git add -A
  git commit -m "feat($ISSUE_IDENTIFIER): agent completed task

Automated commit by Symphony Agent Platform.
Issue: $ISSUE_IDENTIFIER" --allow-empty || true
fi

# 获取当前分支名
BRANCH_NAME="$(git rev-parse --abbrev-ref HEAD)"
echo "[after-run] Pushing branch: $BRANCH_NAME"

# 配置 remote URL（带 token 认证）
REMOTE_URL="https://${GITHUB_TOKEN}@github.com/${GITHUB_OWNER}/${GITHUB_REPO}.git"
git remote set-url origin "$REMOTE_URL" 2>/dev/null || git remote add origin "$REMOTE_URL"

git push origin "$BRANCH_NAME" --force-with-lease 2>&1 || {
  echo "[after-run] Push failed, trying force push..."
  git push origin "$BRANCH_NAME" --force 2>&1
}

echo "[after-run] Push successful."

# -----------------------------------------------------------------------------
# Step 2: 获取 Linear Issue 标题（用于 PR 标题）
# -----------------------------------------------------------------------------
echo "[after-run] Fetching Linear issue info..."

LINEAR_RESPONSE=$(curl -s -X POST https://api.linear.app/graphql \
  -H "Authorization: $LINEAR_API_KEY" \
  -H "Content-Type: application/json" \
  --max-time 15 \
  -d "{\"query\": \"{ issues(filter: { identifier: { eq: \\\"$ISSUE_IDENTIFIER\\\" } }) { nodes { id title description } } }\"}" 2>/dev/null || echo "{}")

ISSUE_ID=$(echo "$LINEAR_RESPONSE" | python3 -c "
import sys, json
try:
    d = json.load(sys.stdin)
    nodes = d.get('data', {}).get('issues', {}).get('nodes', [])
    print(nodes[0]['id'] if nodes else '')
except:
    print('')
" 2>/dev/null || echo "")

ISSUE_TITLE=$(echo "$LINEAR_RESPONSE" | python3 -c "
import sys, json
try:
    d = json.load(sys.stdin)
    nodes = d.get('data', {}).get('issues', {}).get('nodes', [])
    print(nodes[0]['title'] if nodes else '$ISSUE_IDENTIFIER')
except:
    print('$ISSUE_IDENTIFIER')
" 2>/dev/null || echo "$ISSUE_IDENTIFIER")

echo "[after-run] Issue title: $ISSUE_TITLE"

# -----------------------------------------------------------------------------
# Step 3: 创建 GitHub Pull Request
# -----------------------------------------------------------------------------
echo "[after-run] Creating GitHub PR..."

PR_TITLE="[$ISSUE_IDENTIFIER] $ISSUE_TITLE"
PR_BODY="## Summary

Automated PR created by Symphony Agent Platform.

**Linear Issue:** $ISSUE_IDENTIFIER  
**Branch:** \`$BRANCH_NAME\`

## Changes

Agent completed the task for issue [$ISSUE_IDENTIFIER](https://linear.app/issue/$ISSUE_IDENTIFIER).

> This PR was automatically generated by Symphony. Please review before merging.
"

GITHUB_API_RESPONSE=$(curl -s -X POST \
  -H "Authorization: token $GITHUB_TOKEN" \
  -H "Content-Type: application/json" \
  "https://api.github.com/repos/$GITHUB_OWNER/$GITHUB_REPO/pulls" \
  --max-time 15 \
  -d "$(python3 -c "
import json, sys
print(json.dumps({
  'title': '''$PR_TITLE''',
  'body': '''$PR_BODY''',
  'head': '$BRANCH_NAME',
  'base': '$GITHUB_DEFAULT_BRANCH',
  'draft': False
}))
")" 2>/dev/null || echo "{}")

PR_URL=$(echo "$GITHUB_API_RESPONSE" | python3 -c "
import sys, json
try:
    d = json.load(sys.stdin)
    print(d.get('html_url', ''))
except:
    print('')
" 2>/dev/null || echo "")

PR_ERROR=$(echo "$GITHUB_API_RESPONSE" | python3 -c "
import sys, json
try:
    d = json.load(sys.stdin)
    print(d.get('message', '') or d.get('errors', [{}])[0].get('message', ''))
except:
    print('')
" 2>/dev/null || echo "")

if [ -n "$PR_URL" ]; then
  echo "[after-run] PR created: $PR_URL"
elif echo "$PR_ERROR" | grep -qi "already exists"; then
  echo "[after-run] PR already exists for this branch, skipping creation."
else
  echo "[after-run] WARNING: PR creation failed: $PR_ERROR"
fi

# -----------------------------------------------------------------------------
# Step 4: 更新 Linear Issue 状态为 "In Review"
# -----------------------------------------------------------------------------
if [ -z "$ISSUE_ID" ]; then
  echo "[after-run] WARNING: Could not find Linear issue ID for $ISSUE_IDENTIFIER, skipping state update."
  exit 0
fi

echo "[after-run] Updating Linear issue $ISSUE_IDENTIFIER to 'In Review'..."

LINEAR_UPDATE_RESPONSE=$(curl -s -X POST https://api.linear.app/graphql \
  -H "Authorization: $LINEAR_API_KEY" \
  -H "Content-Type: application/json" \
  --max-time 15 \
  -d "{\"query\": \"mutation { issueUpdate(id: \\\"$ISSUE_ID\\\", input: { stateId: \\\"$LINEAR_IN_REVIEW_STATE_ID\\\" }) { success issue { identifier state { name } } } }\"}" 2>/dev/null || echo "{}")

UPDATE_SUCCESS=$(echo "$LINEAR_UPDATE_RESPONSE" | python3 -c "
import sys, json
try:
    d = json.load(sys.stdin)
    r = d.get('data', {}).get('issueUpdate', {})
    print(r.get('success', False))
except:
    print(False)
" 2>/dev/null || echo "False")

if [ "$UPDATE_SUCCESS" = "True" ]; then
  echo "[after-run] Linear issue $ISSUE_IDENTIFIER updated to 'In Review'."
else
  echo "[after-run] WARNING: Failed to update Linear issue state."
  echo "[after-run] Response: $LINEAR_UPDATE_RESPONSE"
fi

echo "[after-run] Done."
