#!/bin/bash
# Symphony Enterprise Agent Platform - Installation Script
# Usage: curl -fsSL https://symphony.dev/install.sh | bash

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Configuration
SYMPHONY_DIR="${SYMPHONY_DIR:-$HOME/symphony}"
REPO_URL="${REPO_URL:-https://github.com/symphony/symphony.git}"
BUN_INSTALL_URL="https://bun.sh/install"

echo -e "${BLUE}╔════════════════════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║   Symphony Enterprise Agent Platform - Installer      ║${NC}"
echo -e "${BLUE}╚════════════════════════════════════════════════════════╝${NC}"
echo ""

# Check for required commands
check_requirements() {
    echo -e "${YELLOW}Checking requirements...${NC}"

    # Check git
    if ! command -v git &> /dev/null; then
        echo -e "${RED}✗ git is not installed. Please install git first.${NC}"
        exit 1
    fi
    echo -e "${GREEN}✓ git is installed${NC}"

    # Check curl
    if ! command -v curl &> /dev/null; then
        echo -e "${RED}✗ curl is not installed. Please install curl first.${NC}"
        exit 1
    fi
    echo -e "${GREEN}✓ curl is installed${NC}"
}

# Install Bun
install_bun() {
    echo -e "${YELLOW}Installing Bun...${NC}"

    if command -v bun &> /dev/null; then
        echo -e "${GREEN}✓ Bun is already installed: $(bun --version)${NC}"
    else
        curl -fsSL "$BUN_INSTALL_URL" | bash

        # Source bun config
        if [ -f "$HOME/.bashrc" ]; then
            source "$HOME/.bashrc"
        elif [ -f "$HOME/.zshrc" ]; then
            source "$HOME/.zshrc"
        fi

        if command -v bun &> /dev/null; then
            echo -e "${GREEN}✓ Bun installed successfully: $(bun --version)${NC}"
        else
            echo -e "${YELLOW}! Bun installed but not in PATH. Please restart your shell or run:${NC}"
            echo -e "${YELLOW}  export BUN_INSTALL=\"\$HOME/.bun\"${NC}"
            echo -e "${YELLOW}  export PATH=\"\$BUN_INSTALL/bin:\$PATH\"${NC}"
        fi
    fi
}

# Create symphony directory
create_directory() {
    echo -e "${YELLOW}Creating Symphony directory...${NC}"

    if [ -d "$SYMPHONY_DIR" ]; then
        echo -e "${YELLOW}! Directory $SYMPHONY_DIR already exists${NC}"
        read -p "Do you want to overwrite? (y/N): " -n 1 -r
        echo
        if [[ ! $REPLY =~ ^[Yy]$ ]]; then
            echo -e "${RED}Installation cancelled.${NC}"
            exit 1
        fi
        rm -rf "$SYMPHONY_DIR"
    fi

    mkdir -p "$SYMPHONY_DIR"
    echo -e "${GREEN}✓ Created $SYMPHONY_DIR${NC}"
}

# Clone repository
clone_repository() {
    echo -e "${YELLOW}Cloning Symphony repository...${NC}"
    git clone "$REPO_URL" "$SYMPHONY_DIR"
    echo -e "${GREEN}✓ Repository cloned${NC}"
}

# Install dependencies
install_dependencies() {
    echo -e "${YELLOW}Installing dependencies...${NC}"
    cd "$SYMPHONY_DIR"
    bun install
    echo -e "${GREEN}✓ Dependencies installed${NC}"
}

# Interactive configuration
configure_symphony() {
    echo -e "${YELLOW}Configuring Symphony...${NC}"
    echo ""

    # Create .env file
    cat > "$SYMPHONY_DIR/.env" << 'EOF'
# Symphony Configuration
# Generated by install.sh

# Anthropic API Key (required)
ANTHROPIC_API_KEY=

# Telegram Bot Token (optional, for mobile control)
TELEGRAM_BOT_TOKEN=

# Telegram User ID (optional, restrict access)
TELEGRAM_USER_ID=

# Linear API Key (optional, for issue tracking)
LINEAR_API_KEY=

# Linear Project Slug (optional)
LINEAR_PROJECT_SLUG=

# Server Configuration
SERVER_PORT=8080
SERVER_HOST=0.0.0.0

# Workspace Configuration
WORKSPACE_ROOT=./workspaces

# Database Configuration
DATABASE_PATH=./symphony.db
EOF

    echo -e "${GREEN}✓ Created .env template${NC}"
    echo -e "${YELLOW}Please edit $SYMPHONY_DIR/.env with your API keys${NC}"
}

# Create systemd service
create_systemd_service() {
    if [ "$EUID" -ne 0 ]; then
        echo -e "${YELLOW}Skipping systemd service creation (not root)${NC}"
        return
    fi

    echo -e "${YELLOW}Creating systemd service...${NC}"

    cat > /etc/systemd/system/symphony.service << EOF
[Unit]
Description=Symphony Enterprise Agent Platform
After=network.target

[Service]
Type=simple
User=$SUDO_USER
WorkingDirectory=$SYMPHONY_DIR
Environment=PATH=/usr/bin:/home/$SUDO_USER/.bun/bin
ExecStart=$(which bun) run start
Restart=always
RestartSec=10

[Install]
WantedBy=multi-user.target
EOF

    systemctl daemon-reload
    echo -e "${GREEN}✓ Systemd service created${NC}"
    echo -e "${YELLOW}Enable with: systemctl enable symphony && systemctl start symphony${NC}"
}

# Main installation
main() {
    check_requirements
    install_bun
    create_directory
    clone_repository
    install_dependencies
    configure_symphony

    # Try to create systemd service (requires root)
    if [ "$EUID" -eq 0 ]; then
        create_systemd_service
    fi

    echo ""
    echo -e "${GREEN}╔════════════════════════════════════════════════════════╗${NC}"
    echo -e "${GREEN}║           Installation Complete!                       ║${NC}"
    echo -e "${GREEN}╚════════════════════════════════════════════════════════╝${NC}"
    echo ""
    echo -e "${BLUE}Next steps:${NC}"
    echo "  1. Edit configuration: cd $SYMPHONY_DIR && nano .env"
    echo "  2. Add your API keys (ANTHROPIC_API_KEY, TELEGRAM_BOT_TOKEN, etc.)"
    echo "  3. Start the server: bun run start"
    echo "  4. Access dashboard: http://localhost:8080"
    echo ""
    echo -e "${BLUE}Documentation:${NC}"
    echo "  - User Guide: $SYMPHONY_DIR/docs/user-guide.md"
    echo "  - Deployment: $SYMPHONY_DIR/docs/deployment.md"
    echo ""
}

# Run installation
main
